### ISSUE TITLE
Pasting

### ISSUE THREAD

**Issue by probablykasper** [viktorstrate/color-picker-plus#7] opened 2018-06-24 22:01 UTC
Pasting does not work in any text fields.

It would be great if I could paste into the text fields - but, if the clipboard itself is a color code, it should update the color.

You could even check the clipboard automatically once the color picker is opened, and apply the color code in the clipboard if there is one (really useful if I wanna just quickly adjust a color. The old color could be put in "Previous")

**Comment by viktorstrate** [comment] 2018-06-24 23:15
You can paste into all of the fields, but currently the fields only update when the enter key is pressed, or you click away from the field.

But I do however think, that it is a good idea to check the user's clipboard for a colorcode when the extension has loaded.

**Comment by kasper9n** [comment] 2018-06-25 07:30
Sorry, I was thinking of CMD+V pasting.

**Comment by viktorstrate** [comment] 2018-06-25 08:10
CMD+V is working fine for me, but it is probably because, one of the keyboard shortcuts for copying colors already exist in the program you are using, and therefore is getting overwritten with CMD+V.

What program are you using ColorPickerPlus with?
And Is one of the copy-dropdown shortcuts CMD+V?

**Comment by kasper9n** [comment] 2018-06-25 12:15
Not sure exactly what you mean... If it wasn't clear, I meant pasting into the color picker itself. Doesn't work no matter what program I use with it

> And Is one of the copy-dropdown shortcuts CMD+V?

What do you mean by that?

**Comment by viktorstrate** [comment] 2018-06-25 12:28
I have no problem pasting with CMD+V into the different text fields inside the ColorPickerPlus extension.

What I mean is that, if the application you're using already have a shortcut that the copy color drop down also uses, then the colorpicker will automatically find another shortcut that isn't in use.

**Comment by kasper9n** [comment] 2018-06-25 12:37
All the copying shortcuts work perfectly, but using CMD+V gives me a beep sound. The color picker is actually brought up by an extension called [MenuBar Colors](https://github.com/nvzqz/Menubar-Colors). That app is never "focused" though - so when the color picker is open, MenuBar Colors doesn't show up in the top-left beside the Apple logo. It can't be the app I'm actually using - I've tried in VSCode, Chrome and Finder, and it still gives me the beep sound.

**Comment by viktorstrate** [comment] 2018-06-25 12:39
That is odd, I don't know what is causing that.

**Comment by kasper9n** [comment] 2018-06-25 12:51
Really weird how CMD+V doesn't work, but all the other ones do.

Just confirmed pasting works when the color picker is brought up in TextEdit, so it must be the menubar app.

**Comment by viktorstrate** [comment] 2018-06-25 21:39
If you find out that it is a problem with ColorPickerPlus, then please post a comment, and I will reopen this issue.

For now I will close it.

**Closed as completed by viktorstrate** 2018-06-25 21:39 UTC
Labels: bug, help wanted
